update angular material to 17
this is a part of preparation to upgrade to angular 18

PS C:\Users\kushal\src\angular\mycanary> cd "C:\Users\kushal\src\angular\mycanary\"; date; yarn; date; yarn run ng build; date; yarn run ng update; date; yarn run ng update @angular/material@17

Saturday, May 25, 2024 6:12:39 AM
yarn install v1.22.21
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.29s.
Saturday, May 25, 2024 6:12:39 AM
yarn run v1.22.21
$ ng build
✔ Browser application bundle generation complete.
✔ Copying assets complete.
✔ Index html generation complete.

Initial chunk files | Names         |  Raw size
vendor.js           | vendor        |   4.67 MB |
polyfills.js        | polyfills     | 138.66 kB |
styles.css          | styles        |  99.09 kB |
main.js             | main          |  19.85 kB |
runtime.js          | runtime       |   6.34 kB |

                    | Initial total |   4.92 MB

Build at: 2024-05-25T10:12:43.620Z - Hash: 2837c1e99f44bbfe - Time: 2240ms
Done in 4.14s.
Saturday, May 25, 2024 6:12:43 AM
yarn run v1.22.21
$ ng update
Using package manager: yarn
Collecting installed dependencies...
Found 41 dependencies.
    We analyzed your package.json, there are some packages to update:

      Name                                    Version                  Command to update
     -------------------------------------------------------------------------------------
      @angular-eslint/schematics              17.5.0 -> 17.5.1         ng update @angular-eslint/schematics
      @angular/cdk                            17.3.9 -> 18.0.0         ng update @angular/cdk
      @angular/cli                            17.3.7 -> 18.0.1         ng update @angular/cli
      @angular/core                           17.3.9 -> 18.0.0         ng update @angular/core
      @angular/material                       16.2.14 -> 17.3.9        ng update @angular/material@17

    There might be additional packages which don't provide 'ng update' capabilities that are outdated.
    You can update the additional packages by running the update command of your package manager.
Done in 5.12s.
Saturday, May 25, 2024 6:12:48 AM
yarn run v1.22.21
$ ng update @angular/material@17
The installed Angular CLI version is outdated.
Installing a temporary Angular CLI versioned 17.3.8 to perform the update.
✔ Packages successfully installed.
Using package manager: yarn
Collecting installed dependencies...
Found 41 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular/cdk @ "17.3.10" (was "17.3.9")...
    Updating package.json with dependency @angular/material @ "17.3.10" (was "16.2.14")...
UPDATE package.json (1777 bytes)
✔ Packages successfully installed.
** Executing migrations of package '@angular/material' **

> Updates Angular Material to v17.

      ✓  Updated Angular Material to version 17

  Migration completed (No changes made).

Done in 81.67s.

PS C:\Users\kushal\src\angular\mycanary>

build failed, removing more legacy

PS C:\Users\kushal\src\angular\mycanary> cd "C:\Users\kushal\src\angular\mycanary\"; date; yarn; date; yarn run ng build; date; yarn run ng update; date;

Saturday, May 25, 2024 6:14:56 AM
yarn install v1.22.21
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.29s.
Saturday, May 25, 2024 6:14:56 AM
yarn run v1.22.21
$ ng build
✔ Browser application bundle generation complete.

./src/custom-theme.scss - Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Undefined mixin.
   ╷
18 │ @include mat.all-legacy-component-typographies();
   │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  src\custom-theme.scss 18:1  root stylesheet

./src/custom-theme.scss?ngGlobalStyle - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Undefined mixin.
   ╷
18 │ @include mat.all-legacy-component-typographies();
   │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  src\custom-theme.scss 18:1  root stylesheet

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Saturday, May 25, 2024 6:15:31 AM
yarn run v1.22.21
$ ng update
Using package manager: yarn
Collecting installed dependencies...
Found 41 dependencies.
    We analyzed your package.json, there are some packages to update:

      Name                                    Version                  Command to update
     -------------------------------------------------------------------------------------
      @angular-eslint/schematics              17.5.0 -> 17.5.1         ng update @angular-eslint/schematics
      @angular/cdk                            17.3.10 -> 18.0.0        ng update @angular/cdk
      @angular/cli                            17.3.7 -> 18.0.1         ng update @angular/cli
      @angular/core                           17.3.9 -> 18.0.0         ng update @angular/core
      @angular/material                       17.3.10 -> 18.0.0        ng update @angular/material

    There might be additional packages which don't provide 'ng update' capabilities that are outdated.
    You can update the additional packages by running the update command of your package manager.
Done in 10.03s.
Saturday, May 25, 2024 6:15:41 AM

PS C:\Users\kushal\src\angular\mycanary>

PS C:\Users\kushal\src\angular\mycanary> cd "C:\Users\kushal\src\angular\mycanary\"; date; yarn; date; yarn run ng build; date; yarn run ng update; date;

Saturday, May 25, 2024 6:16:42 AM
yarn install v1.22.21
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.29s.
Saturday, May 25, 2024 6:16:43 AM
yarn run v1.22.21
$ ng build
✔ Browser application bundle generation complete.

./src/custom-theme.scss - Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Undefined mixin.
   ╷
43 │ @include mat.all-legacy-component-themes($mycanary-theme);
   │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  src\custom-theme.scss 43:1  root stylesheet

./src/custom-theme.scss?ngGlobalStyle - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Undefined mixin.
   ╷
43 │ @include mat.all-legacy-component-themes($mycanary-theme);
   │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  src\custom-theme.scss 43:1  root stylesheet

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Saturday, May 25, 2024 6:16:49 AM
yarn run v1.22.21
$ ng update
Using package manager: yarn
Collecting installed dependencies...
Found 41 dependencies.
    We analyzed your package.json, there are some packages to update:

      Name                                    Version                  Command to update
     -------------------------------------------------------------------------------------
      @angular-eslint/schematics              17.5.0 -> 17.5.1         ng update @angular-eslint/schematics
      @angular/cdk                            17.3.10 -> 18.0.0        ng update @angular/cdk
      @angular/cli                            17.3.7 -> 18.0.1         ng update @angular/cli
      @angular/core                           17.3.9 -> 18.0.0         ng update @angular/core
      @angular/material                       17.3.10 -> 18.0.0        ng update @angular/material

    There might be additional packages which don't provide 'ng update' capabilities that are outdated.
    You can update the additional packages by running the update command of your package manager.
Done in 4.79s.
Saturday, May 25, 2024 6:16:54 AM

PS C:\Users\kushal\src\angular\mycanary>

PS C:\Users\kushal\src\angular\mycanary> cd "C:\Users\kushal\src\angular\mycanary\"; date; yarn; date; yarn run ng build; date; yarn run ng update; date;

Saturday, May 25, 2024 6:17:47 AM
yarn install v1.22.21
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.29s.
Saturday, May 25, 2024 6:17:47 AM
yarn run v1.22.21
$ ng build
✔ Browser application bundle generation complete.
✔ Copying assets complete.
✔ Index html generation complete.

Initial chunk files | Names         |  Raw size
vendor.js           | vendor        |   4.75 MB |
polyfills.js        | polyfills     | 138.66 kB |
main.js             | main          |  19.85 kB |
runtime.js          | runtime       |   6.34 kB |
styles.css          | styles        |   2.44 kB |

                    | Initial total |   4.91 MB

Build at: 2024-05-25T10:17:53.872Z - Hash: 0efaddec27b7259e - Time: 4360ms
Done in 6.24s.
Saturday, May 25, 2024 6:17:53 AM
yarn run v1.22.21
$ ng update
Using package manager: yarn
Collecting installed dependencies...
Found 41 dependencies.
    We analyzed your package.json, there are some packages to update:

      Name                                    Version                  Command to update
     -------------------------------------------------------------------------------------
      @angular-eslint/schematics              17.5.0 -> 17.5.1         ng update @angular-eslint/schematics
      @angular/cdk                            17.3.10 -> 18.0.0        ng update @angular/cdk
      @angular/cli                            17.3.7 -> 18.0.1         ng update @angular/cli
      @angular/core                           17.3.9 -> 18.0.0         ng update @angular/core
      @angular/material                       17.3.10 -> 18.0.0        ng update @angular/material

    There might be additional packages which don't provide 'ng update' capabilities that are outdated.
    You can update the additional packages by running the update command of your package manager.
Done in 5.69s.
Saturday, May 25, 2024 6:17:59 AM